// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljyuklzmxsfmashvktpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqeXVrbHpteHNmbWFzaHZrdHB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjMzNDMsImV4cCI6MjA2OTAzOTM0M30.yTjgHSjBSNIxPk6Br_b434KZbxvkAk1Js8xS05C43_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});